name: Publish to Docker/DockerHub
on:
  push:
    branches:
      - develop  # Cambia esto si deseas ejecutar en otras ramas también

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check source code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build application
        run: |
          ./mvnw package  # O el comando que uses para construir tu JAR

      - name: Get image tag
        id: tags
        shell: bash
        run: |
          echo "::set-output name=version::0.1"  # Aquí puedes usar un método para obtener dinámicamente el número de versión

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_NAMESPACE }}/backend:${{ steps.tags.outputs.version }}
            ${{ secrets.DOCKER_HUB_NAMESPACE }}/backend:latest

