name: Publish to Docker/DockerHub
on:
  push:
    branches:
      - develop

      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Build with Maven
        run: mvn clean package  # Asegúrate de que este comando se adapte a tu proyecto

      - name: Get image tag
        id: tags
        run: |
          version=$(grep 'FROM' $GITHUB_WORKSPACE/Dockerfile | awk -F':' '{print $2}' | awk -F'-' '{print $1}')
          echo "version=$version" >> $GITHUB_ENV

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_NAMESPACE }}/backend:latest
            ${{ secrets.DOCKER_HUB_NAMESPACE }}/backend:${{ env.version }}
